<?php

/**
 * @file
 * Contains faculty_view.module
 */

function byu_faculty_directory_theme() {
    return [
        'node__byu_faculty_member' => [
            'base hook' => 'node',
            'template' => 'node--byu-faculty-member',
        ],
        'views_view_fields__faculty_directory_listing' => [
            'base hook' => 'views-view-fields',
            'template' => 'views-view-fields--faculty-directory-listing',
        ],
    ];
}